### ISSUE TITLE
OpenSSL Source Repository

### ISSUE THREAD

**Issue by hyperxpro** [corretto/amazon-corretto-crypto-provider#107]
Currently, ACCP uses `openssl-1.1.1f.tar.gz` but if in future OpenSSL releases a new patch, `openssl-1.1.1f.tar.gz` will get moved in `/source/old` which can break the ACCP building process because OpenSSL will return HTTP 404 for the file.

**Comment by hyperxpro** [comment]
Patch for this done in Netty-TCNative: https://github.com/netty/netty-tcnative/pull/539

Can we implement a fallback to `source/old` directory incase of HTTP 404?

**Comment by SalusaSecondus** [comment]
Likely strategy for this follows:
https://stackoverflow.com/questions/34234820/gradle-exec-task-returns-non-zero-exit-value-and-fails-the-build-but-i-want-to-n

**Comment by hyperxpro** [comment]
Thanks a lot!
