### ISSUE TITLE
Enable to preextract the native lib

### ISSUE THREAD

**Issue by rmannibucau** [corretto/amazon-corretto-crypto-provider#140]
Hi,

I'd like to be able to use corretto native lib already extracted (using build to do that and put it properly in a docker image).
Goal is to make this part of the code https://github.com/corretto/amazon-corretto-crypto-provider/blob/develop/src/com/amazon/corretto/crypto/provider/Loader.java#L110 just a System.load(<system property>).
It is close to loader logic of sigar and enables to save a lot of slowness at startup in containers.

Is it possible to get such a feature?

Romain

**Comment by SalusaSecondus** [comment]
Thank you. This is a change we're discussing but have no current plans to share.
