### ISSUE TITLE
fips-2

### ISSUE THREAD

**Issue by listaction** [corretto/amazon-corretto-crypto-provider#164]
hi folks, 
looking at the repo readme i see : `Currently algorithms are primarily backed by OpenSSL's implementations (1.1.1j as of ACCP 1.6.0) but this may change in the future.`

Thus if we build a fips-2 compliant openssl  ( I am able to do that with amazonlinux2 and addition of dracut-fips) and use that as a the base image for corretto would it be work effectively?  

this was the only past issue i could find related to this : https://github.com/corretto/amazon-corretto-crypto-provider/issues/66

**Comment by SalusaSecondus** [comment]
Sorry for the long delay in responding to this.

We have not tested ACCP with any other builds of OpenSSL and so cannot speak to its correctness or whether it will fill your FIPS requirements. You should specifically be aware that the current version of ACCP implements its own DRBG and implements HMAC directly on top of the raw hash functions. Both of these may cause problems for you.

You are not the only person who has asked us for a FIPS solution and we hear you. Unfortunately we do not have any plans that we can share at this time.
