### ISSUE TITLE
TLS SSLContext not available when using JDK 15

### ISSUE THREAD

**Issue by Cai-Chen** [corretto/amazon-corretto-crypto-provider#175]
Hi, I am using ACCP in OpenSearch 1.2.4 and get an error when configure `Djava.security.properties=/mypath/amazon-corretto-crypto-provider.security`

> Feb 11 02:09:50 ip-10-1-40-70 opensearch[1787]: [2022-02-11T02:09:50,196][ERROR][o.o.s.s.DefaultSecurityKeyStore] [ip-10-1-40-70] Unable to determine supported ciphers due to
Feb 11 02:09:50 ip-10-1-40-70 opensearch[1787]: java.security.NoSuchAlgorithmException: TLS SSLContext not available
Feb 11 02:09:50 ip-10-1-40-70 opensearch[1787]:         at sun.security.jca.GetInstance.getInstance(GetInstance.java:159) ~[?:?]
Feb 11 02:09:50 ip-10-1-40-70 opensearch[1787]:         at javax.net.ssl.SSLContext.getInstance(SSLContext.java:184) ~[?:?]
Feb 11 02:09:50 ip-10-1-40-70 opensearch[1787]:         at org.opensearch.security.ssl.DefaultSecurityKeyStore.initEnabledSSLCiphers(DefaultSecurityKeyStore.java:805) [opensearch-security-1.2.4.0.jar:1.2.4.0]

I traced back into DefaultSecurityKeyStore.java:805 in https://github.com/opensearch-project/security/blob/7ebb2ca045e6ff259c5c8084762eee5656820e33/src/main/java/org/opensearch/security/ssl/DefaultSecurityKeyStore.java#L805 and its just ` final SSLContext serverContext = SSLContext.getInstance("TLS");`

But when I switch back to JDK 11, it is working.

So is there any issue with JDK 15 and above or anything I need configure manually?

**Comment by Cai-Chen** [comment]
Looks like some JDK 15 & 17 cannot handle these 2 providers:

> Mar 01 05:33:56 ip-10-0-9-70 opensearch[8970]: ProviderConfig: Error loading legacy provider sun.security.ec.SunEC
Mar 01 05:33:56 ip-10-0-9-70 opensearch[8970]: java.security.PrivilegedActionException: java.lang.IllegalAccessException: class sun.security.jca.ProviderConfig$ProviderLoader$1 (in module java.base) cannot access class sun.security.ec.SunEC (in module jdk.crypto.ec) because module jdk.crypto.ec does not export sun.security.ec to module java.base
Mar 01 05:33:56 ip-10-0-9-70 opensearch[8970]:         at java.base/java.security.AccessController.doPrivileged(AccessController.java:573)

> Mar 01 05:33:56 ip-10-0-9-70 opensearch[8970]: ProviderConfig: Loading legacy provider: com.sun.net.ssl.internal.ssl.Provider
Mar 01 05:33:56 ip-10-0-9-70 opensearch[8970]: ProviderConfig: Error loading legacy provider com.sun.net.ssl.internal.ssl.Provider
Mar 01 05:33:56 ip-10-0-9-70 opensearch[8970]: java.lang.ClassNotFoundException: com.sun.net.ssl.internal.ssl.Provider
Mar 01 05:33:56 ip-10-0-9-70 opensearch[8970]:         at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)

After commenting `sun.security.ec.SunEC` and `com.sun.net.ssl.internal.ssl.Provider`, its working fine.

**Comment by SalusaSecondus** [comment]
Interesting. Previously the same config would work for both old versions of java and newer versions as well (since things would fall back correctly). It seems we need to have different versions of this configuration for JDK15 and newer.

Thank you very much for reporting this (along with the solution). I'm glad you have something that works for you while we get this fixed more generally.
