### ISSUE TITLE
Please provide aarch64 builds ;)

### ISSUE THREAD

**Issue by lizthegrey** [corretto/amazon-corretto-crypto-provider#206]
https://aws.amazon.com/blogs/developer/tuning-apache-kafka-and-confluent-platform-for-graviton2-using-amazon-corretto/

It would have been a lot less work if I'd just been able to download and add to classpath a JAR, hint hint.

for your next release, would it be possible to do builds for each arch (or build a single multi-arch jar?)

**Comment by lizthegrey** [comment]
Work being tracked in https://issues.amazon.com/issues/CryptoAlg-1101

**Comment by WillChilds-Klein** [comment]
hi! it was really happy to read [your blog post](https://aws.amazon.com/blogs/developer/tuning-apache-kafka-and-confluent-platform-for-graviton2-using-amazon-corretto/) earlier today. as far as I know, it's the first customer win we've heard of for ACCP-on-ARM (which has thus far achieved only "experimental" support). great work!

we already have [an issue](https://github.com/corretto/amazon-corretto-crypto-provider/issues/40) for tracking ARM support whose scope, although perhaps not explicitly, includes vending ARM-targeted build artifacts.

do you mind if i dedupe/close this issue in favor of our pre-existing one?

**Comment by WillChilds-Klein** [comment]
official ARM builds are on our roadmap, and we're actively working on them. until that's released, our ARM support is "experimental". you can build (or script the building of) ACCP on an ARM host and use the resulting JAR.

**Comment by tylerbenson** [comment]
@WillChilds-Klein Do you have a ballpark ETA?  The last release was over a year ago...

**Comment by WillChilds-Klein** [comment]
we don't have a public ETA at this time.

**Comment by luneo7** [comment]
For those like me that wanted to use ACCP on Graviton... I've built an aarch64 version of the latest release and published it:
```
<dependency>
  <groupId>io.github.luneo7</groupId>
  <artifactId>AmazonCorrettoCryptoProvider</artifactId>
  <version>1.6.1</version>
  <classifier>linux-aarch_64</classifier>
</dependency>
```
It is not a signed provider (because I have no Oracle cert...), so it doesn't work with OracleJDK, but with any OpenJDK variant (like Amazon Corretto) it will work =]

**Comment by lizthegrey** [comment]
I see 2.0.0 is coming (https://github.com/corretto/amazon-corretto-crypto-provider/pull/260/files) -- does this mean a toolchain revamp is in progress so we get aarch64 at same time as x86_64?

**Comment by WillChilds-Klein** [comment]
yes.

**Comment by amirhosv** [comment]
ACCP 2.0.0 is released and available from Maven and the Github release pages. ARM64 builds are also available.
