### ISSUE TITLE
Automatically pick up new tests added to test directory

### ISSUE THREAD

**Issue by alexw91** [corretto/amazon-corretto-crypto-provider#239]
### Problem:
Currently, our [CMakeLists.txt has a hardcoded lists of tests](https://github.com/corretto/amazon-corretto-crypto-provider/blob/21172da62e81e97e56fa15691ae8dbe59b7d450c/CMakeLists.txt#L554-L608) that requires updating every time tests are added or removed.  

### Solution:
We should update our CMake build to automatically scan our test directory and run every test in it.

Previous Discussion: https://github.com/corretto/amazon-corretto-crypto-provider/pull/235#discussion_r922504266

**Comment by WillChilds-Klein** [comment]
Turns out this was pretty straightforward. I [have a PR in the works](https://github.com/WillChilds-Klein/amazon-corretto-crypto-provider/pull/1/files#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20a) that should address this.
