### ISSUE TITLE
FIP 140-3 certification plans?

### ISSUE THREAD

**Issue by anoop9** [corretto/amazon-corretto-crypto-provider#249]
I would like to know if the Amazon-corretto-crypto-provider library is  planning to get  a FIPS- 140-3 certification in near future from NIST -(https://csrc.nist.gov/Projects/cryptographic-module-validation-program/modules-in-process/Modules-In-Process-List )?  I can see that AWS LC (libcrypto) is in review process for FIPS 140-3. So wanted to know if this java library has any similar plans.

**Comment by brian-jarvis-aws** [comment]
Hello, my apologies for the delayed response here. ACCP by itself does not contain cryptography which would be subject to FIPS certification. Rather, it is built upon an underlying native libcrypto library which may be FIPS certified. For our recent [ACCP 2 release](https://github.com/corretto/amazon-corretto-crypto-provider/releases/latest), we have switched to using AWS-LC as the underlying libcrypto library. As you pointed out, AWS-LC is currently in the NIST queue for FIPS 140-3 certification. Once that certification is complete, we will release a version of ACCP which uses the FIPS mode of AWS-LC. Unfortunately, we cannot offer a date when that will occur. It depends on when NIST completes their review process.
