### ISSUE TITLE
Add performance metrics

### ISSUE THREAD

**Issue by SalusaSecondus** [corretto/amazon-corretto-crypto-provider#25]
Consumers need a way to efficiently gather performance metrics. This must be optional and when enabled add minimal overhead to operations.

**Comment by WillChilds-Klein** [comment]
what level of granularity would be most useful here? callers can measure wall clock latencies themselves if desired, but exposing more granular latency metrics risks exposing implementation details that users may come to rely on.

is the motivation user convenience (e.g JMX metrics for public method latency) or something more internal?

**Comment by geedo0** [comment]
Resolving as stale and underspecified. While I agree that adding more telemetry is generally useful, we can open a new issue when we have crisper requirements around specific metrics, technical limitations, and general approach.
