### ISSUE TITLE
Why adopt native openssl library for Java please？

### ISSUE THREAD

**Issue by superajun-wsj** [corretto/amazon-corretto-crypto-provider#254]
Why does corretto adopt native openssl for Java while not adopting jca or third library boucy castle? Is the performance of  openssl much better than bouncy castle?

**Comment by WillChilds-Klein** [comment]
Yes, for ACCP 1.x (backed by OpenSSL's libcrypto), the primary advantage of ACCP over Bouncy Castle is performance.

In 2.0, ACCP drops its dependency on OpenSSL and uses [AWS-LC](https://github.com/awslabs/aws-lc/) as its native backing crypto library. performance benchmarks of ACCP 2.0 against Bouncy Castle show as much as an order of magnitude speedup for most algorithms. Benchmarks against SunJCE providers (many of which also use native code for hardware acceleration) show some speedups, but not as pronounced as Bouncy Castle.

**Comment by stanpalatnik** [comment]
@WillChilds-Klein Is it possible to swap out AWS-LC for OpenSSL3 since OpenSSL3 is already FIPS validated?

**Comment by WillChilds-Klein** [comment]
There are currently no plans to support OpenSSL 3 as a backing crypto library in ACCP.

Stay tuned for [ACCP's upcoming 2.3.0 release](https://github.com/corretto/amazon-corretto-crypto-provider/pull/316), which will provide ACCP artifacts using AWS-LC built in FIPS mode on Maven Central. Please note that AWS-LC is still awaiting its FIPS certificate, so you please consult your team's compliance expert regarding the implications of that for your projects.
