### ISSUE TITLE
[question] Is there a public release schedule?

### ISSUE THREAD

**Issue by carterkozak** [corretto/amazon-corretto-crypto-provider#256]
This project solves a set of problems that many of us share, however it's difficult to depend upon without understanding goals around release frequency, particularly if/when vulnerabilities are discovered in this library or its dependencies (aws-lc/boringssl).

Building forks is certainly an option to control upgrade frequency, however there's something to be said for broader use of a single artifact for validation, and it's not clear that we're better off with N forks if the goal isn't to add nonstandard features. Would it be reasonable to release at a predictable cadence, using the latest stable aws-lc?

aws-libcrypto has produced several releases since the most recent release of ACCP (1.6.1 at the time of writing).
This repo has had [216 commits since the latest release](https://github.com/corretto/amazon-corretto-crypto-provider/compare/46cb685bb3d6a1819297ac5ea65a09d31fa66cab...c235ecd5a90c56b0f3d2c7deb7345d448891a69e).

Any insight you can provide would be greatly appreciated, thanks!

**Comment by amirhosv** [comment]
We are currently working on enhancing our CI/CD and release pipelines in preparation for an upcoming major release. A result of this will be more frequent releases. This development is expected to be done this month.

**Comment by carterkozak** [comment]
That’s fantastic to hear, thanks!

**Comment by varikin** [comment]
Any update on this? We are planning on upgrading to Java 17 later this year and we would prefer an official release with the fix to the list of security providers for Java 17.

**Comment by SalusaSecondus** [comment]
(I am not a maintainer anymore and my answer is provided as an individual.)

The policy files within [etc](https://github.com/corretto/amazon-corretto-crypto-provider/tree/develop/etc) are safe to use with the 1.x releases of ACCP. So you can just grab them now and use them with whatever version of ACCP you already have working.

**Comment by varikin** [comment]
@SalusaSecondus Good to know. I just know it's preferable from a compliance stand point to say I'm using a release, not patching a release, especially since this is crypto software. I know this isn't quite patching, but it's edging close to patching since I have to grab a file from main to add to a previous release.

**Comment by SalusaSecondus** [comment]
(I am not a maintainer anymore and my answer is provided as an individual.)

ACCP really is the jar and there are *lots* of different (documented in the readme) ways to configure it. One of them even tells you to look at those files as an example of what that change would look like. The configuration files aren't even included in the artifacts which are published to Maven. While I absolutely cannot speak to your compliance concerns, I wouldn't even consider this a patch, rather just a different way of configuring the exact same version :-)

**Comment by amirhosv** [comment]
We are testing the release pipeline and reviewing the process. This January, we will have a major release.

**Comment by amirhosv** [comment]
ACCP 2.0.0 is released! It's available both from Maven and Github release pages.
