### ISSUE TITLE
Support without AWS-LC

### ISSUE THREAD

**Issue by Eonfge** [corretto/amazon-corretto-crypto-provider#269]
## Background

With version [2.0.0](https://github.com/corretto/amazon-corretto-crypto-provider/blob/develop/CHANGELOG.md#200-unreleased), ACCP gets a new back-end which is based on a custom fork of Boring SSL. This introduces a lot of problems for people with existing implementations, their own servers, or their own images based on different versions of Linux. Part of that I discuss here: https://github.com/awslabs/aws-lc/issues/804

## Current issue

The problem right now, is that I don't know if AWS-CL is a hard dependency or if ACCP stays functional when a custom image doesn't have AWS-CL. Images based on RHEL or Ubuntu won't have AWS-CL, and building AWS-CL is unreasonable as mentioned in the issue with AWS-CL.

## Actions
- Clarify:
  - Does 2.0.0 still work on stock RHEL, Ubuntu, CentOS Stream?
- Documentation:
  - Update the documentation so that there is no confusion

**Comment by amirhosv** [comment]
ACCP 2.0.0 requires AWS-LC, but it doesn't need it to be installed system wide. ACCP includes all the shared objects (SOs) it needs, including `libcrypto.so` for AWS-LC, as part of the bundled Jar file.

**Comment by Eonfge** [comment]
That's good to know. Is this something to add to the documentation? #270

**Comment by amirhosv** [comment]
It totally makes sense. Thanks for the PR. I'm resolving this issue now.
