### ISSUE TITLE
AmazonCorrettoCryptoProvider.install should return position of installed provider

### ISSUE THREAD

**Issue by smiklosovic** [corretto/amazon-corretto-crypto-provider#313]
There is method in `AmazonCorrettoCryptoProvider`

    public static void install() {
        Security.insertProviderAt(INSTANCE, 1);
    }

This method returns `void` but what it could return is `int` because `insertProviderAt` returns the position where it was installed or -1 if it was installed already, from Javadoc:

_the actual preference position in which the provider was added, or -1 if the provider was not added because it is already installed._

Otherwiwse, how do I know that I have installed it already?

**Comment by geedo0** [comment]
We certainly have the opportunity to provide better assurances at intall() time given that information from the return value. I can bring this suggestion to the team and see what they think.

> Otherwiwse, how do I know that I have installed it already?
If your primary concern is asserting that the installation was successful we provide [this](https://github.com/corretto/amazon-corretto-crypto-provider#verification-optional) specific guidance for that case. Is that sufficient or is there a reason for preferring this new method that you suggest?

**Comment by geedo0** [comment]
The team decided to stay with the current interface. We have concerns around breaking common static analysis rules our customers have in their builds once we start returning a value in this method. In addition to validating successful installation, our guidance also validates correct preference order and health.
