### ISSUE TITLE
CMake Error - Could NOT find JNI (missing: JAVA_AWT_LIBRARY JAVA_AWT_INCLUDE_PATH)

### ISSUE THREAD

**Issue by jocull** [corretto/amazon-corretto-crypto-provider#318]
Hi, I'm getting this error when trying to do a build from a fresh clone. I am not sure what I am missing or what it is trying to tell me. I believe I installed all the components listed in the README and have the Corretto JDK selected. I am running inside an Ubuntu 22.04 container with aarch64.

```
-- Set runtime path of "/build/amazon-corretto-crypto-provider/build/awslc/bin/bin/bssl" to ""
make: Leaving directory '/build/amazon-corretto-crypto-provider/build/awslc/build'

> Task :executeCmake FAILED
-- The C compiler identification is GNU 11.4.0
-- The CXX compiler identification is GNU 11.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Java: /usr/bin/java (found suitable version "11.0.20", minimum required is "10")
CMake Error at /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find JNI (missing: JAVA_AWT_LIBRARY JAVA_AWT_INCLUDE_PATH)
Call Stack (most recent call first):
  /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.22/Modules/FindJNI.cmake:382 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:31 (find_package)

-- Configuring incomplete, errors occurred!
```

My `CMakeOutput` log is attached: [CMakeOutput.log](https://github.com/corretto/amazon-corretto-crypto-provider/files/12231140/CMakeOutput.log)

**Comment by WillChilds-Klein** [comment]
Hi @jocull, a few questions:

1. What commands are you using to clone and build?
2. Have you set the `JAVA_HOME` environment variable in your shell?

We have a sample Dockerfile [here](https://github.com/corretto/amazon-corretto-crypto-provider/blob/main/Dockerfile.dev) that some folks on the team use when developing ACCP.

**Comment by jocull** [comment]
The Dockerfile helps, I can work with that 😄  Not sure what was wrong exactly with my local machine. I didn't have the `JAVA_HOME` set initially, but it didn't seem to make a difference after I did set it. Inside the container I'm able to do a full build with `./gradlew release` 🎉 

My next issue is I'm trying to make a FIPS build. On the `main` branch this fails with some kind of Makefile error. I thought there might be an issue with the `aws-lc` submodule since it is pointing at `v1.5.0` tag after a fresh clone? (Using `git clone --recurse-submodules [url]`)

I know this is experimental right now, but should it be working in 2.x? It does seem to work if I checkout the tag for `1.6.2` on this repo.

**Comment by jocull** [comment]
I believe I figured this out. FIPS needs Perl and Golang 1.18 --confusing because Golang 1.13 is the default Ubuntu 20.04 version and the error is not clear unless you're building `aws-lc` directly. PR is up to help future devs 🙂

**Comment by WillChilds-Klein** [comment]
Ok, PR #319 is merged so I'm going to close this out. Please feel free to re-open with any additional questions or suggestions.
