### ISSUE TITLE
ACCP not loading in Tomcat 9.0.45 with Java 17

### ISSUE THREAD

**Issue by sxv6975** [corretto/amazon-corretto-crypto-provider#328]
Tried multiple things but the verification always fails when checking if ACCP was used as the security provider.

I tried verification using 
```if (Cipher.getInstance("AES/GCM/NoPadding").getProvider().getName().equals(AmazonCorrettoCryptoProvider.PROVIDER_NAME)```
This is happening on application built with Java 17 and running on tomcat 9.0.45. Tomcat is using Java 17 as well.
I tried adding the jar file to $CATALINA_HOME/lib, applications WEB-INF/lib, lib dir under java, etc.  It was always picking up SunJCE as the provider.

The only way I could make it was to add it to the classpath of the tomcat process startup command. java.security file was updated to use ACCP as the preferred provider (reordered rest of them), I tried using -Djava.security.properties system property as well to the one mentioned in this repo. 

I am using ACCP 1.4.0 version since that was what used previously within our app for encrypting data.

Any suggestions or help on how to proceed.

**Comment by WillChilds-Klein** [comment]
Hi, a few questions to help diagnose:

1. Are you able to install programmatically as described [here](https://github.com/corretto/amazon-corretto-crypto-provider#code)?
2. We have a [distinct security.properties file for JDK15+](https://github.com/corretto/amazon-corretto-crypto-provider/blob/main/etc/amazon-corretto-crypto-provider-jdk15.security). Are you using that?
3. It sounds like this codebase was previously using ACCP 1.4.0, what's changed to cause your issue?

**Comment by sxv6975** [comment]
@WillChilds-Klein - thanks for the response
1. I didn't try the programatic way
2. I am using the [distinct security.properties file for JDK15+](https://github.com/corretto/amazon-corretto-crypto-provider/blob/main/etc/amazon-corretto-crypto-provider-jdk15.security).
3. We are upgrading java and previously we added the jar directly to jvm/lib/ext but the newer versions of java don't have this directory anymore so trying to figure out way to get this done

**Comment by geedo0** [comment]
This issue doesn't seem specific to ACCP, are you able to load other libraries using the `$CATALINA_HOME/lib` directory? Something's up with the classpath when configuring the Tomcat server and we can't provide too much guidance on how to troubleshoot that. AFAICT from [this documentation](https://tomcat.apache.org/tomcat-9.0-doc/class-loader-howto.html), `$CATALINA_HOME/lib` (maybe try `$CATALINA_BASE/lib` as well?) is still the correct place to place jars on the latest version of Tomcat.

Checking and/or overriding the `common.loader` property in `$CATALINA_BASE/conf/catalina.properties` also seems like a promising path to follow.

**Comment by luizhespanha** [comment]
@sxv6975 Did ou make some progress?
I'm with a similar issue, but I'm using jdk21 and Jetty 9.4.x.
I can confirm that ACCP is in the classpath, and the tests:
```
if (AmazonCorrettoCryptoProvider.INSTANCE.getLoadingError() == null && AmazonCorrettoCryptoProvider.INSTANCE.runSelfTests().equals(SelfTestStatus.PASSED)) {
    // Successfully installed
}
```
and 
```
AmazonCorrettoCryptoProvider.INSTANCE.assertHealthy();
```
returns that ACCP is successfully installed.

But the test
```
if (Cipher.getInstance("AES/GCM/NoPadding").getProvider().getName().equals(AmazonCorrettoCryptoProvider.PROVIDER_NAME)) {
    // Successfully installed
}
```
always returns SunJCE.

I'm trying passing the security.properties from jdk15+ using the -Djava.security.properties. Unfortunately, there's no logs in the JVM initialization that can help me too :(

**Comment by luizhespanha** [comment]
Just an update, it works when I created a XML with:
```
<?xml version="1.0"?>
<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "http://www.eclipse.org/jetty/configure_9_3.dtd">

<Configure id="Server" class="org.eclipse.jetty.server.Server">
  <Call class="com.amazon.corretto.crypto.provider.AmazonCorrettoCryptoProvider" name="install"></Call>
</Configure>
```
and reference this XML in my ssd.mod file.

Using `-Djava.security.properties` or changing the `java.security` file directly didn't work for Jetty. It worked when I started a simple Main program without using Jetty, but it didn't work when I started the Jetty with `java -jar start.jar`.

Just posting here because maybe it can help someone in the future.
