### ISSUE TITLE
ACCP for FIPS compliant JSSE provider

### ISSUE THREAD

**Issue by k-raina** [corretto/amazon-corretto-crypto-provider#340]
We are trying to asses ACCP for FIPS compliant for SSL implementation

We didn't notice any JSSE provider, Is there any special attention needed to make TrustStore and KeyStore FIPS compliant?

**Comment by WillChilds-Klein** [comment]
ACCP FIPS does not currently provide a JSSE provider implementation. It exposes Java bindings for the FIPS-validated AWS-LC cryptographic module via the JCA. It's possible that ACCP FIPS could be used to build a JSSE provider; we would strongly recommend consulting your local compliance expert when evaluating the requirements for such a project.
