### ISSUE TITLE
Allow configuration of tmpdir to avoid issues with noexec on java.io.tmpdir

### ISSUE THREAD

**Issue by christopherincanada** [corretto/amazon-corretto-crypto-provider#359]
**NOT A CONTRIBUTION**

ACCP uses `java.io.tmpdir` as the location to extract native libraries to. However, if that directory has been mounted with the `noexec` option, as is the case with the `/tmp` directory on many Linux systems, ACCP will fail to load with an error like the following:

```
Exception in thread "main" com.amazon.corretto.crypto.provider.RuntimeCryptoException: Unable to load native library
at Caused by: 
com.amazon.corretto.crypto.provider.AmazonCorrettoCryptoProvider.assertHealthy(AmazonCorrettoCryptoProvider.java:517)
java.lang.UnsatisfiedLinkError: /tmp/libamazonCorrettoCryptoProvider87cd5202885576a3.so: failed to map segment from shared object: Operation not permitted
```

The above results from a call to `AmazonCorrettoCryptoProvider.INSTANCE.assertHealthy()`.

To workaround this issue it would nice if ACCP would provide a system property like `com.amazon.corretto.crypto.provider.tmpdir` that could be used to specify which temp directory for ACCP to use. When not provided it could default to the value of the `java.io.tmpdir` system property.

Also open to other ideas for how to address the issue. Another solution is to simply update `java.io.tmpdir` to point it to a different directory not mounted with `noexec`, but that effects everything not just ACCP, which may not be desirable.

**Comment by amirhosv** [comment]
@christopherincanada Thanks for reporting this. The proposal to add a new system property to specify a custom temp directory for ACCP is reasonable. I'll submit a PR that and it will be included in our next release.

**Comment by amirhosv** [comment]
The PR for addressing the issue has been merged.
