### ISSUE TITLE
Provide an Uber Jar (in addition to the platform-specific Jars)

### ISSUE THREAD

**Issue by humanzz** [corretto/amazon-corretto-crypto-provider#366]
Hello,

This is a request to provide an Uber jar that has the different platforms bindings, in addition to the existing platform-specific jars.

This is an approach followed by https://github.com/awslabs/aws-crt-java (check their README for the Uber vs. Platform-specific Jars) which for those that are not space-sensitive, can lead to simplified build configurations.

**Comment by amirhosv** [comment]
Hi Ahmed. Thanks for reporting this. We have an internal ticket to track this.

**Comment by humanzz** [comment]
Hello,
Just checking in on this.
Lambda has recently released ARM/SnapStart support, which is the main motivation behind my initial request.
An Uber Jar would really simplify some of our build processes, to enable the transitioning to ARM (given we can handle the jar size increases).

**Comment by WillChilds-Klein** [comment]
resolving in favor of #409
