### ISSUE TITLE
Register SecureRandom by default for FIPS version

### ISSUE THREAD

**Issue by torben-hansen** [corretto/amazon-corretto-crypto-provider#379]
The README states:
> For performance reasons, ACCP does not register a SecureRandom implementation in FIPS mode. Relevant operations within the FIPS module boundary (e.g. key generation, non-deterministic signing, etc.) will still use AWS-LC's internal DRBG. Users who require ACCP to provide FIPS-validated pseudo-randomness outside the module boundary via SecureRandom should set registerSecureRandom=true.

However, the conditions that spawned this decision are no longer true since [AWS-LC-FIPS-2.0.0](https://github.com/aws/aws-lc/releases/tag/AWS-LC-FIPS-2.0.0). This version (and newer) use "Passive Entropy" as default entropy source which have different performance characteristics.

Consider registering SecureRandom by default making it a tad easier to consume ACCP-FIPS correctly.

**Comment by WillChilds-Klein** [comment]
resolved in PR #385
