### ISSUE TITLE
Support OSX

### ISSUE THREAD

**Issue by SalusaSecondus** [corretto/amazon-corretto-crypto-provider#41]
Fully Support OSX

**Comment by kiwi1969** [comment]
I am interested in what this ticket is asking...
Can someone please expand on what is actually missing in OSX (if anything)

Ie. Today I added the ACCP Linux x86 jar to CLASSPATH via .zlogin script, installed Corretto8 JDK, changed java.security file to have ACCP as first in list.
When I run a test to show active providers, it prints the AACP as first in list, showing it is indeed installed.
If I remove from classpath, I get the previous list without AACP
From reading, I could use other JDK such as Adopt OpenJDK, and AACP should still work.

I believe ACCP has no impact on OpenSSL, Boring SSL, Libre SSL, Conscript, OKHTTP, but will enhance certain other security methods. I believe OSX pretends to have OpenSSL but has own internals, but can be thought of as OpenSSL
(Please correct me if I am wrong with the no-impact on OpenSSL comment)

**Comment by SalusaSecondus** [comment]
ACCP uses a native library to perform its cryptography which contains a statically linked copy of OpenSSL. The form of these libraries is different depending on operating system. (Linux uses SO files, Windows uses DLLs, and OSX uses dynlibs.) So, while you may have seen ACCP in your provider list, I would be surprised it if advertised any supported algorithms. Instead, it detected that it was on an unsupported system and silently disabled itself so that Java falls back to the standard implementations and continues to work. (This makes it safe to use ACCP even when you aren't sure if the end system will support it. They may not have the performance benefits, but at least they will still run.)

I recommend trying your experiment and calling this method to see if ACCP is actually fully functional:
```java
AmazonCorrettoCryptoProvider.INSTANCE.assertHealthy();
```

I'm not sure what your question is from the last part of your comment. What do you mean by "no impact" and what are you trying to achieve?

**Comment by Taffer** [comment]
If ACCP is now using AWS-LC for crypto, is this Issue obsolete now?

**Comment by samuel40791765** [comment]
Not necessarily, although AWS-LC is buildable on OSX, ACCP itself still doesn't fully have build support for OSX yet. The same issues when ACCP was building with OpenSSL still apply.
