### ISSUE TITLE
AES/CBC/NoPadding does not encrypt ByteBuffer slices correctly

### ISSUE THREAD

**Issue by bmathiske** [corretto/amazon-corretto-crypto-provider#411]
If "AES/CBC/NoPadding" is used to encrypt several disjoint `ByteBuffer` slices from the same underlying byte array, each slice's positioning is relative to the array's beginning instead of to the respective slice's offset into the underlying byte array. This leads to garbled output that cannot be decrypted.

This bug was found by Guillaume Rose and Aline Bousquet at Apple. They also provided a reproducer program, which has been used to create unit testing for this issue. See the commits in the PR below.

**Comment by amirhosv** [comment]
Thanks for catching and fixing this.
