### ISSUE TITLE
ECDHE support

### ISSUE THREAD

**Issue by samer-shami** [corretto/amazon-corretto-crypto-provider#46]
Is there a possibility that the ECDHE Key Agreement will be supported in future releases?

**Comment by SalusaSecondus** [comment]
By "ECDHE" do you mean "ephemeral ECDH as used in TLS cipher-suites"? If so, then the actual algorithm being used is ECDH and we already support it. If this isn't what you mean, can you help us to understand exactly which algorithms you want?

**Comment by samer-shami** [comment]
I do indeed mean "ephemeral elliptic curve diffie hellman". I had an issue with an endpoint that only supported ECDHE. I assumed that since you mentioned only ECDH that was the cause of the issue. I thought that ACCP didn't support the ephemeral version of the key exchange. 

So, in actual fact, ACCP does support the ephemeral version of DH?

**Comment by SalusaSecondus** [comment]
Yes, ACCP does support the ephemeral versions of DH and ECDH and we've tested it with ECDHE cipher suites.

What issues are you seeing?

**Comment by samer-shami** [comment]
I followed the README.md and set the security.provider list to that shown below in Corretto 11.0.4.11.1 under Ubuntu 18.04 Linux:
```
security.provider.1=com.amazon.corretto.crypto.provider.AmazonCorrettoCryptoProvider
security.provider.2=sun.security.provider.Sun
security.provider.3=sun.security.rsa.SunRsaSign
security.provider.4=sun.security.ec.SunEC
security.provider.5=com.sun.net.ssl.internal.ssl.Provider
security.provider.6=com.sun.crypto.provider.SunJCE
security.provider.7=sun.security.jgss.SunProvider
security.provider.8=com.sun.security.sasl.Provider
security.provider.9=org.jcp.xml.dsig.internal.dom.XMLDSigRI
security.provider.10=sun.security.smartcardio
security.provider.11=sun.security.provider.certpath.ldap.JdkLDAP
security.provider.12=com.sun.security.sasl.gsskerb.JdkSASL
security.provider.13=apple.security.AppleProvider
security.provider.14=sun.security.mscapi.SunMSCAPI
security.provider.15=sun.security.pkcs11SunPKCS11
```

I had an issue connecting to a website that only accepted ECDHE key exchanges. The Java app  was not able to connect. It wasn't until I added the following to security.providers (they were the values that were previously there in the java.security file)
```
security.provider.16=SUN
security.provider.17=SunRsaSign
security.provider.18=SunEC
security.provider.19=SunJSSE
security.provider.20=SunJCE
security.provider.21=SunJGSS
security.provider.22=SunSASL
security.provider.23=XMLDSig
security.provider.24=SunPCSC
security.provider.25=JdkLDAP
security.provider.26=JdkSASL
security.provider.27=SunPKCS11
``` 

After the security.provider config was 27 long, the app could then connect via ECDHE.

The verification:
```
if (Cipher.getInstance("AES/GCM/NoPadding").getProvider().getName().equals(AmazonCorrettoCryptoProvider.PROVIDER_NAME)) {
	// Successfully installed
}
```
was successful whether the security.provider was the recommended 15 or the final 27 that I had. However, I do not know any more if it is using ACCP to connect via ECDHE.

**Comment by SalusaSecondus** [comment]
Thank you. It looks like the providers are being configured in a slightly different way on your system. I think we have enough to debug this and I'll dig into it.

As far as whether you are using ACCP for your ciphers and ECDHE key agreement? In all likelihood yes. The verification tells us that it is properly configured as the highest priority and would be used whenever possible.

**Comment by samer-shami** [comment]
Hi. Thanks for that. To add a clarification, I used the java.security that came with Corretto 11 and made the following changes:
1) Changed security.provider to the list of 27 as detailed previously.
2) Changed securerandom.strongAlgorithms to that in the amazon-corretto-crypto-provider.security file.
3) Changed ```jdk.tls.disabledAlgorithms=SSLv3, TLSv1.1, RC4, MD5, DES, MD5withRSA, DH keySize < 1024, EC keySize < 224, 3DES_EDE_CBC, anon, NULL, DSA, KRB5, DHE_DSS, ECDH, ECDSA```

**Comment by SalusaSecondus** [comment]
Thank you for the detailed report. I've been able to reproduce and root-cause this issue. Modules were introduced in Java 9 and this changed how providers were loaded. The modules which contain Java's default providers do not export the constructors of the providers but rather them to be addressed by name.  See the following exception
```
ProviderConfig: Loading legacy provider: sun.security.ec.SunEC
ProviderConfig: Error loading legacy provider sun.security.ec.SunEC
java.security.PrivilegedActionException: java.lang.IllegalAccessException: class sun.security.jca.ProviderConfig$ProviderLoader$1 (in module java.base) cannot access class sun.security.ec.SunEC (in module jdk.crypto.ec) because module jdk.crypto.ec does not export sun.security.ec to module java.base
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/sun.security.jca.ProviderConfig$ProviderLoader.legacyLoad(ProviderConfig.java:392)
        at java.base/sun.security.jca.ProviderConfig$ProviderLoader.load(ProviderConfig.java:358)
        at java.base/sun.security.jca.ProviderConfig$3.run(ProviderConfig.java:244)
        at java.base/sun.security.jca.ProviderConfig$3.run(ProviderConfig.java:238)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/sun.security.jca.ProviderConfig.doLoadProvider(ProviderConfig.java:238)
        at java.base/sun.security.jca.ProviderConfig.getProvider(ProviderConfig.java:218)
        at java.base/sun.security.jca.ProviderList.loadAll(ProviderList.java:315)
        at java.base/sun.security.jca.ProviderList.removeInvalid(ProviderList.java:332)
        at java.base/sun.security.jca.Providers.getFullProviderList(Providers.java:173)
        at java.base/java.security.Security.getProviders(Security.java:455)
        at Dump.main(Dump.java:6)
Caused by: java.lang.IllegalAccessException: class sun.security.jca.ProviderConfig$ProviderLoader$1 (in module java.base) cannot access class sun.security.ec.SunEC (in module jdk.crypto.ec) because module jdk.crypto.ec does not export sun.security.ec to module java.base
        at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:361)
        at java.base/jdk.internal.reflect.Reflection.ensureMemberAccess(Reflection.java:99)
        at java.base/java.lang.Class.newInstance(Class.java:579)
        at java.base/sun.security.jca.ProviderConfig$ProviderLoader$1.run(ProviderConfig.java:395)
        at java.base/sun.security.jca.ProviderConfig$ProviderLoader$1.run(ProviderConfig.java:392)
        ... 13 more
ProviderConfig: Error loading provider sun.security.ec.SunEC
```

We do have a few paths forward for patching this file and will fix it shortly. Once again, thank you very much for this report.

**Comment by samer-shami** [comment]
Thank you for looking into it. I will take the updated security.provider list as the master list and update my end.

**Comment by SalusaSecondus** [comment]
Test builds have now been updated to explicitly test on multiple versions of Java and detect this error.
