### ISSUE TITLE
FIPS

### ISSUE THREAD

**Issue by a-hansen** [corretto/amazon-corretto-crypto-provider#66]
Is FIPS compliance in your future?

**Comment by ttjsu-aws** [comment]
Thanks for reaching out, Aaron! We are investigating your question and will reply back on this thread when we have made a determination. We appreciate your patience.

**Comment by SalusaSecondus** [comment]
Thank you for letting us know your interest in this. However, at this time we have no current plans to develop a FIPS validated version of this library.

**Comment by hyperxpro** [comment]
> Thank you for letting us know your interest in this. However, at this time we have no current plans to develop a FIPS validated version of this library.

If we build this library with OpenSSL FIPS then it should comply with FIPS 140-2. Am I right?

**Comment by trustin** [comment]
@hyperxpro Did you succeed to build it with OpenSSL FIPS?
